---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: 'yes'
    update_cache: yes

- name: "remove unused dependencies"
  become: yes
  apt:
    autoremove: true

- name: "install node and npm"
  become: yes
  apt:
    name:
      - nodejs
      - npm
    state: latest
    update_cache: true

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present