Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup     
      KeyName: apacheServer # If you use another key pair name, please put here
      # Ubuntu 18 or higher works fine for your region
      ImageId: ami-0b0dcb5067f052a63
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}

Outputs: 
  InstanceDNSName: 
    Description: A reference to the created EC2 url
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub EC2InstanceDNSName-${ID}
